# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170521_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postings',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thread'),
        ),
    ]
