# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170522_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postings',
            name='imagelink',
            field=models.CharField(max_length=200),
        ),
    ]
